# Generated by Django 3.2.6 on 2021-08-23 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0003_alter_usercard_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_name', models.CharField(max_length=300, verbose_name='Название теста')),
                ('education_type', models.CharField(choices=[('PE', 'Периодическое обучение'), ('FE', 'Первичное обучение')], default='PE', max_length=30, verbose_name='Тип обучения')),
                ('respondents', models.ManyToManyField(to='education.UserCard', verbose_name='Респонденты')),
            ],
            options={
                'ordering': ['poll_name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_question', models.CharField(max_length=500, verbose_name='Текст вопроса')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.poll', verbose_name='Вопрос из теста')),
            ],
            options={
                'ordering': ['poll'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.CharField(max_length=500, verbose_name='Ответ на вопрос')),
                ('is_right', models.BooleanField(verbose_name='Правильный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question', verbose_name='Ответ')),
            ],
            options={
                'ordering': ['question'],
            },
        ),
    ]
