# Generated by Django 3.2.6 on 2021-08-23 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_poll_education_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['question'], 'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['poll_name'], 'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['poll'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.RemoveField(
            model_name='poll',
            name='education_type',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='respondents',
        ),
    ]
