# Generated by Django 3.2.6 on 2021-08-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20210823_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='poll_name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Название теста'),
        ),
    ]
