# Generated by Django 3.2.6 on 2021-08-19 06:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import education.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivision_name', models.CharField(max_length=20, verbose_name='Аббревиатура подразделения')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['subdivision_name'],
            },
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ФИО пользователя')),
                ('education', models.TextField(verbose_name='Образование')),
                ('education_profile', models.CharField(max_length=80, verbose_name='Профиль образования')),
                ('receipt', models.DateField(verbose_name='Дата приема')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=75, unique=True)),
                ('subdivision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.subdivision', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PeriodEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('YE', 'Годовое обучение'), ('SE', 'Обучение по подразделениям')], default='YE', max_length=30, verbose_name='Тип периодического обучения')),
                ('test_issueng_date', models.DateField(verbose_name='Дата выдачи тестовых заданий')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Дата сдачи')),
                ('percent_of_complete', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Процент выполнения')),
                ('pe_file', models.FileField(blank=True, upload_to=education.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['xlsx', 'docx'])], verbose_name='Подтверждение обучения')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.usercard', verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Периодическое обучение',
                'verbose_name_plural': 'Периодические обучения',
            },
        ),
        migrations.CreateModel(
            name='FirstEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, verbose_name='Дата сдачи')),
                ('estimate', models.BooleanField(null=True, verbose_name='Отметка о сдаче')),
                ('fe_file', models.FileField(blank=True, upload_to=education.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['xlsx', 'docx'])], verbose_name='Подтверждение обучения')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.usercard', verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Первичное обучение',
                'verbose_name_plural': 'Первичные обучения',
            },
        ),
    ]
