# Generated by Django 3.2.6 on 2021-08-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdivision',
            name='subdivision_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Аббревиатура подразделения'),
        ),
    ]
