# Generated by Django 3.2.6 on 2021-08-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_subdivision_subdivision_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=75),
        ),
    ]
