# Generated by Django 3.2.6 on 2021-08-24 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20210823_1349'),
        ('education', '0003_alter_usercard_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='firsteducation',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.poll'),
        ),
    ]
