# Generated by Django 3.2.6 on 2021-09-20 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('education', '0005_alter_firsteducation_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercard',
            name='subdivision',
        ),
        migrations.AlterField(
            model_name='firsteducation',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user', verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='periodeducation',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user', verbose_name='ФИО'),
        ),
        migrations.DeleteModel(
            name='Subdivision',
        ),
        migrations.DeleteModel(
            name='UserCard',
        ),
    ]
